set(OPENSSL_FOUND TRUE)
set(OPENSSL_VERSION "3.0.0")

if(MSVC)
    set(OPENSSL_SSL_LIBRARY "${BORINGSSL_OUTPUT_DIR}/ssl.lib")
    set(OPENSSL_CRYPTO_LIBRARY "${BORINGSSL_OUTPUT_DIR}/crypto.lib")
else()
    set(OPENSSL_SSL_LIBRARY "${BORINGSSL_OUTPUT_DIR}/libssl.a")
    set(OPENSSL_CRYPTO_LIBRARY "${BORINGSSL_OUTPUT_DIR}/libcrypto.a")
endif()

set(OPENSSL_LIBRARIES "${OPENSSL_SSL_LIBRARY};${OPENSSL_CRYPTO_LIBRARY}")
set(OPENSSL_INCLUDE_DIR "${BORINGSSL_INCLUDE_DIR}")
set(OPENSSL_INCLUDE_DIRS "${OPENSSL_INCLUDE_DIR}")
set(OPENSSL_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/extern/boringssl/")

# Create the imported targets
if(NOT TARGET OpenSSL::SSL)
    add_library(OpenSSL::SSL STATIC IMPORTED GLOBAL)
    set_target_properties(OpenSSL::SSL PROPERTIES
        IMPORTED_LOCATION "${OPENSSL_SSL_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${BORINGSSL_INCLUDE_DIR}"
    )
endif()

if(NOT TARGET OpenSSL::Crypto)
    add_library(OpenSSL::Crypto STATIC IMPORTED GLOBAL)
    set_target_properties(OpenSSL::Crypto PROPERTIES
        IMPORTED_LOCATION "${OPENSSL_CRYPTO_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${BORINGSSL_INCLUDE_DIR}"
    )
endif()
