#include "lute/stdlib.h"

// This file provides lutestdlib and is auto-generated by luthier.py.
// If it is not present or outdated, re-configure using luthier.py.
#include "generated/modules.h"

#include <string_view>
#include <utility>

StdLibModuleResult getStdLibModule(std::string_view path)
{
    for (const auto& [pathInLib, contents] : lutestdlib)
    {
        if (path != pathInLib)
            continue;

        if (contents == "#directory")
            return {StdLibModuleType::Directory};
        else
            return {StdLibModuleType::Module, contents};
    }

    return {StdLibModuleType::NotFound};
}
