name: build

on:
  push:
    branches: ["primary"]
  pull_request:
    branches: ["primary"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            options: --c-compiler=cl.exe --cxx-compiler=cl.exe
          - os: ubuntu-latest
            options: --c-compiler=gcc --cxx-compiler=g++
          - os: ubuntu-latest
            options: --c-compiler=clang --cxx-compiler=clang++
          - os: macos-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Build Lute
        uses: ./.github/actions/setup-and-build
        with:
          config: debug
          options: ${{ matrix.options }}

  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run StyLua
        run: stylua --check .

  aggregator:
    name: Gated Commits
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }}
    steps:
      - name: Aggregate
        run: |
          echo "All required jobs completed"
