name: build

on:
  push:
    branches: ["primary"]
  pull_request:
    branches: ["primary"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
            options: --c-compiler=gcc --cxx-compiler=g++
          - os: ubuntu-latest
            options: --c-compiler=clang --cxx-compiler=clang++
          - os: macos-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup and Build Lute
        uses: ./.github/actions/setup-and-build
        with:
          config: debug
          options: ${{ matrix.options }}

  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Run StyLua
        run: stylua --check .
