#include "clicommands.h"

// This file provides luteclicommands and is auto-generated by luthier.luau.
// If it is not present or outdated, re-configure using luthier.luau.
#include "generated/commands.h"

#include <array>
#include <string_view>
#include <utility>

CliModuleResult getCliModule(std::string_view path)
{
    for (const auto& [pathInLib, contents] : luteclicommands)
    {
        if (path != pathInLib)
            continue;

        if (contents == "#directory")
            return {CliModuleType::Directory};
        else
            return {CliModuleType::Module, contents};
    }

    return {CliModuleType::NotFound};
}

std::optional<CliCommandResult> getCliCommand(std::string_view command)
{
    const std::array<std::string, 2> pathOptions = {"@cli/" + std::string(command) + ".luau", "@cli/" + std::string(command) + "/init.luau"};

    for (const std::string& path : pathOptions)
    {
        CliModuleResult result = getCliModule(path);
        if (result.type == CliModuleType::Module)
        {
            return CliCommandResult{result.contents, path};
        }
    }

    return std::nullopt;
}
